# Inspección de datos para el dashboard

Este notebook tiene como objetivo explorar la estructura del archivo de salida del modelo (`model_output.parquet`), con el fin de entender las variables disponibles para la construcción del dashboard en Streamlit.

Se busca identificar:
- Columnas disponibles
- Tipos de datos
- Variables clave como el nivel de riesgo y el score

In [2]:
import pandas as pd

df = pd.read_parquet("C:\\Universidad\\2026-1\\proyecto_aplicado_TIC_I\\MONITOREO_TI\\data\\output\\model_output.parquet")
df.head()

            timestamp  risk_score risk_level
0 2020-02-01 00:00:00    0.088449       BAJO
1 2020-02-01 00:00:10    0.087011       BAJO
2 2020-02-01 00:00:19    0.086304       BAJO
3 2020-02-01 00:00:29    0.086120       BAJO
4 2020-02-01 00:00:39    0.084908       BAJO

In [3]:
df.columns

Index(['timestamp', 'risk_score', 'risk_level'], dtype='str')

## Análisis de variables

Se identifican las variables clave para el dashboard:

- `timestamp`: permite visualizar la evolución en el tiempo
- `risk_score`: indicador numérico del riesgo
- `risk_level`: categorización del riesgo (BAJO, MEDIO, ALTO)

Estas variables serán utilizadas para:
- Visualización de tendencias
- Generación de alertas
- Construcción de indicadores en el dashboard

In [4]:
df.describe()

                        timestamp    risk_score
count                     1516948  1.516948e+06
mean   2020-05-16 22:58:36.631517  1.066819e-01
min           2020-02-01 00:00:00  0.000000e+00
25%    2020-03-23 05:05:04.500000  5.521729e-02
50%           2020-05-17 08:07:06  8.173923e-02
75%    2020-07-10 03:07:27.500000  1.230414e-01
max           2020-09-01 03:59:50  1.000000e+00
std                           NaN  8.393937e-02

In [5]:
df["risk_level"].value_counts()

risk_level
BAJO     1487499
MEDIO      28721
ALTO         728
Name: count, dtype: int64